name: Deploy to production

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy the application to EC2
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2
      with:
        node-version: 16

    - name: Configure AWS credentials
      uses: easingthemes/ssh-deploy@main
      with:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOST: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_DNS }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        script: |
          pm2 stop all
          cd server/application/healthhabits-back/
          git pull origin main
          npm run build
          pm2 start all
          pm2 reload healthhabits-back 
